[build]
  publish = "."

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/byt/:cislo"
  to = "/byt-detail.html?cislo=:cislo"
  status = 200
